/**
 * Static reference geography for the North Eastern Region (NER).
 * Coordinates are approximate district centroids used for demo visualisation.
 */

export type NerState =
  | "Assam"
  | "Arunachal Pradesh"
  | "Manipur"
  | "Meghalaya"
  | "Mizoram"
  | "Nagaland"
  | "Sikkim"
  | "Tripura";

export interface DistrictRef {
  id: string;
  name: string;
  state: NerState;
  lat: number;
  lng: number;
  /** Mean terrain slope in degrees (SRTM-derived, demo values). */
  slope: number;
  /** Mean elevation in metres. */
  elevation: number;
  /** Recorded landslide events in the demo historical archive. */
  historicalEvents: number;
  /** Population of the settlements inside monitored slope buffers. */
  exposedPopulation: number;
  /** Index 0-1 describing hill cutting / road-cut density. */
  roadCutIndex: number;
  /** Dominant soil / lithology class. */
  soilClass: "Sandy loam" | "Clayey" | "Loamy skeletal" | "Fine loamy" | "Coarse loamy";
}

export const DISTRICTS: DistrictRef[] = [
  // Meghalaya — highest rainfall belt in the region
  {
    id: "ML-EKH",
    name: "East Khasi Hills",
    state: "Meghalaya",
    lat: 25.467,
    lng: 91.88,
    slope: 38,
    elevation: 1496,
    historicalEvents: 14,
    exposedPopulation: 2340,
    roadCutIndex: 0.82,
    soilClass: "Loamy skeletal",
  },
  {
    id: "ML-WKH",
    name: "West Khasi Hills",
    state: "Meghalaya",
    lat: 25.52,
    lng: 91.28,
    slope: 32,
    elevation: 1420,
    historicalEvents: 9,
    exposedPopulation: 1810,
    roadCutIndex: 0.61,
    soilClass: "Loamy skeletal",
  },
  {
    id: "ML-EJH",
    name: "East Jaintia Hills",
    state: "Meghalaya",
    lat: 25.36,
    lng: 92.37,
    slope: 35,
    elevation: 1180,
    historicalEvents: 11,
    exposedPopulation: 1520,
    roadCutIndex: 0.78,
    soilClass: "Clayey",
  },
  {
    id: "ML-WGH",
    name: "West Garo Hills",
    state: "Meghalaya",
    lat: 25.51,
    lng: 90.22,
    slope: 24,
    elevation: 610,
    historicalEvents: 6,
    exposedPopulation: 1240,
    roadCutIndex: 0.44,
    soilClass: "Fine loamy",
  },
  {
    id: "ML-RB",
    name: "Ri Bhoi",
    state: "Meghalaya",
    lat: 25.899,
    lng: 91.886,
    slope: 30,
    elevation: 940,
    historicalEvents: 8,
    exposedPopulation: 1390,
    roadCutIndex: 0.69,
    soilClass: "Loamy skeletal",
  },

  // Sikkim
  {
    id: "SK-EAST",
    name: "Gangtok",
    state: "Sikkim",
    lat: 27.3314,
    lng: 88.6138,
    slope: 41,
    elevation: 1650,
    historicalEvents: 17,
    exposedPopulation: 3120,
    roadCutIndex: 0.86,
    soilClass: "Loamy skeletal",
  },
  {
    id: "SK-NORTH",
    name: "Mangan",
    state: "Sikkim",
    lat: 27.509,
    lng: 88.529,
    slope: 45,
    elevation: 2100,
    historicalEvents: 13,
    exposedPopulation: 1180,
    roadCutIndex: 0.74,
    soilClass: "Loamy skeletal",
  },
  {
    id: "SK-SOUTH",
    name: "Namchi",
    state: "Sikkim",
    lat: 27.167,
    lng: 88.363,
    slope: 36,
    elevation: 1350,
    historicalEvents: 10,
    exposedPopulation: 2020,
    roadCutIndex: 0.72,
    soilClass: "Coarse loamy",
  },
  {
    id: "SK-WEST",
    name: "Gyalshing",
    state: "Sikkim",
    lat: 27.283,
    lng: 88.26,
    slope: 39,
    elevation: 1780,
    historicalEvents: 12,
    exposedPopulation: 1460,
    roadCutIndex: 0.67,
    soilClass: "Loamy skeletal",
  },

  // Arunachal Pradesh
  {
    id: "AR-PAP",
    name: "Papum Pare",
    state: "Arunachal Pradesh",
    lat: 27.08,
    lng: 93.62,
    slope: 34,
    elevation: 1120,
    historicalEvents: 9,
    exposedPopulation: 2260,
    roadCutIndex: 0.7,
    soilClass: "Coarse loamy",
  },
  {
    id: "AR-WKA",
    name: "West Kameng",
    state: "Arunachal Pradesh",
    lat: 27.26,
    lng: 92.4,
    slope: 43,
    elevation: 2200,
    historicalEvents: 11,
    exposedPopulation: 1340,
    roadCutIndex: 0.76,
    soilClass: "Loamy skeletal",
  },
  {
    id: "AR-TAW",
    name: "Tawang",
    state: "Arunachal Pradesh",
    lat: 27.586,
    lng: 91.859,
    slope: 46,
    elevation: 3048,
    historicalEvents: 8,
    exposedPopulation: 980,
    roadCutIndex: 0.8,
    soilClass: "Loamy skeletal",
  },
  {
    id: "AR-LOH",
    name: "Lohit",
    state: "Arunachal Pradesh",
    lat: 27.89,
    lng: 96.17,
    slope: 37,
    elevation: 1240,
    historicalEvents: 7,
    exposedPopulation: 1120,
    roadCutIndex: 0.58,
    soilClass: "Coarse loamy",
  },
  {
    id: "AR-SIA",
    name: "East Siang",
    state: "Arunachal Pradesh",
    lat: 28.07,
    lng: 95.33,
    slope: 33,
    elevation: 990,
    historicalEvents: 10,
    exposedPopulation: 1580,
    roadCutIndex: 0.62,
    soilClass: "Fine loamy",
  },
  {
    id: "AR-CHA",
    name: "Changlang",
    state: "Arunachal Pradesh",
    lat: 27.13,
    lng: 96.26,
    slope: 35,
    elevation: 1080,
    historicalEvents: 6,
    exposedPopulation: 1210,
    roadCutIndex: 0.55,
    soilClass: "Coarse loamy",
  },

  // Assam
  {
    id: "AS-KAM",
    name: "Kamrup Metropolitan",
    state: "Assam",
    lat: 26.1445,
    lng: 91.7362,
    slope: 18,
    elevation: 55,
    historicalEvents: 12,
    exposedPopulation: 4820,
    roadCutIndex: 0.88,
    soilClass: "Fine loamy",
  },
  {
    id: "AS-DIM",
    name: "Dima Hasao",
    state: "Assam",
    lat: 25.3,
    lng: 93.02,
    slope: 36,
    elevation: 730,
    historicalEvents: 16,
    exposedPopulation: 2140,
    roadCutIndex: 0.81,
    soilClass: "Clayey",
  },
  {
    id: "AS-KAA",
    name: "Karbi Anglong",
    state: "Assam",
    lat: 25.83,
    lng: 93.43,
    slope: 29,
    elevation: 620,
    historicalEvents: 13,
    exposedPopulation: 2670,
    roadCutIndex: 0.66,
    soilClass: "Clayey",
  },
  {
    id: "AS-CAC",
    name: "Cachar",
    state: "Assam",
    lat: 24.8333,
    lng: 92.7789,
    slope: 21,
    elevation: 130,
    historicalEvents: 7,
    exposedPopulation: 3110,
    roadCutIndex: 0.54,
    soilClass: "Fine loamy",
  },
  {
    id: "AS-DIB",
    name: "Dibrugarh",
    state: "Assam",
    lat: 27.4728,
    lng: 94.912,
    slope: 12,
    elevation: 108,
    historicalEvents: 3,
    exposedPopulation: 1890,
    roadCutIndex: 0.36,
    soilClass: "Sandy loam",
  },
  {
    id: "AS-GOA",
    name: "Goalpara",
    state: "Assam",
    lat: 26.17,
    lng: 90.62,
    slope: 16,
    elevation: 42,
    historicalEvents: 4,
    exposedPopulation: 1460,
    roadCutIndex: 0.39,
    soilClass: "Sandy loam",
  },
  {
    id: "AS-SON",
    name: "Sonitpur",
    state: "Assam",
    lat: 26.63,
    lng: 92.8,
    slope: 14,
    elevation: 78,
    historicalEvents: 3,
    exposedPopulation: 1320,
    roadCutIndex: 0.33,
    soilClass: "Sandy loam",
  },

  // Manipur
  {
    id: "MN-IME",
    name: "Imphal East",
    state: "Manipur",
    lat: 24.81,
    lng: 94.0,
    slope: 22,
    elevation: 790,
    historicalEvents: 6,
    exposedPopulation: 2410,
    roadCutIndex: 0.6,
    soilClass: "Clayey",
  },
  {
    id: "MN-NON",
    name: "Noney",
    state: "Manipur",
    lat: 24.83,
    lng: 93.56,
    slope: 40,
    elevation: 1080,
    historicalEvents: 15,
    exposedPopulation: 1620,
    roadCutIndex: 0.84,
    soilClass: "Loamy skeletal",
  },
  {
    id: "MN-TAM",
    name: "Tamenglong",
    state: "Manipur",
    lat: 24.98,
    lng: 93.51,
    slope: 38,
    elevation: 1260,
    historicalEvents: 11,
    exposedPopulation: 1290,
    roadCutIndex: 0.73,
    soilClass: "Loamy skeletal",
  },
  {
    id: "MN-CHU",
    name: "Churachandpur",
    state: "Manipur",
    lat: 24.33,
    lng: 93.68,
    slope: 34,
    elevation: 1150,
    historicalEvents: 9,
    exposedPopulation: 1710,
    roadCutIndex: 0.65,
    soilClass: "Coarse loamy",
  },
  {
    id: "MN-UKH",
    name: "Ukhrul",
    state: "Manipur",
    lat: 25.05,
    lng: 94.36,
    slope: 37,
    elevation: 1662,
    historicalEvents: 8,
    exposedPopulation: 1180,
    roadCutIndex: 0.62,
    soilClass: "Loamy skeletal",
  },

  // Mizoram
  {
    id: "MZ-AIZ",
    name: "Aizawl",
    state: "Mizoram",
    lat: 23.7271,
    lng: 92.7176,
    slope: 39,
    elevation: 1132,
    historicalEvents: 14,
    exposedPopulation: 2980,
    roadCutIndex: 0.87,
    soilClass: "Loamy skeletal",
  },
  {
    id: "MZ-LUN",
    name: "Lunglei",
    state: "Mizoram",
    lat: 22.88,
    lng: 92.73,
    slope: 36,
    elevation: 1200,
    historicalEvents: 10,
    exposedPopulation: 1640,
    roadCutIndex: 0.71,
    soilClass: "Loamy skeletal",
  },
  {
    id: "MZ-SER",
    name: "Serchhip",
    state: "Mizoram",
    lat: 23.3,
    lng: 92.85,
    slope: 34,
    elevation: 1100,
    historicalEvents: 7,
    exposedPopulation: 1080,
    roadCutIndex: 0.64,
    soilClass: "Coarse loamy",
  },
  {
    id: "MZ-KOL",
    name: "Kolasib",
    state: "Mizoram",
    lat: 24.22,
    lng: 92.68,
    slope: 31,
    elevation: 870,
    historicalEvents: 6,
    exposedPopulation: 940,
    roadCutIndex: 0.58,
    soilClass: "Clayey",
  },

  // Nagaland
  {
    id: "NL-KOH",
    name: "Kohima",
    state: "Nagaland",
    lat: 25.67,
    lng: 94.11,
    slope: 40,
    elevation: 1444,
    historicalEvents: 13,
    exposedPopulation: 2380,
    roadCutIndex: 0.85,
    soilClass: "Loamy skeletal",
  },
  {
    id: "NL-DIM",
    name: "Dimapur",
    state: "Nagaland",
    lat: 25.91,
    lng: 93.73,
    slope: 17,
    elevation: 145,
    historicalEvents: 4,
    exposedPopulation: 2130,
    roadCutIndex: 0.42,
    soilClass: "Sandy loam",
  },
  {
    id: "NL-PHE",
    name: "Phek",
    state: "Nagaland",
    lat: 25.67,
    lng: 94.5,
    slope: 38,
    elevation: 1524,
    historicalEvents: 9,
    exposedPopulation: 1120,
    roadCutIndex: 0.63,
    soilClass: "Loamy skeletal",
  },
  {
    id: "NL-MOK",
    name: "Mokokchung",
    state: "Nagaland",
    lat: 26.32,
    lng: 94.52,
    slope: 35,
    elevation: 1325,
    historicalEvents: 8,
    exposedPopulation: 1290,
    roadCutIndex: 0.66,
    soilClass: "Coarse loamy",
  },
  {
    id: "NL-TUE",
    name: "Tuensang",
    state: "Nagaland",
    lat: 26.27,
    lng: 94.83,
    slope: 37,
    elevation: 1371,
    historicalEvents: 7,
    exposedPopulation: 1040,
    roadCutIndex: 0.6,
    soilClass: "Loamy skeletal",
  },

  // Tripura
  {
    id: "TR-WES",
    name: "West Tripura",
    state: "Tripura",
    lat: 23.8315,
    lng: 91.2868,
    slope: 15,
    elevation: 65,
    historicalEvents: 3,
    exposedPopulation: 1980,
    roadCutIndex: 0.46,
    soilClass: "Fine loamy",
  },
  {
    id: "TR-DHA",
    name: "Dhalai",
    state: "Tripura",
    lat: 23.93,
    lng: 91.9,
    slope: 26,
    elevation: 320,
    historicalEvents: 6,
    exposedPopulation: 1160,
    roadCutIndex: 0.55,
    soilClass: "Clayey",
  },
  {
    id: "TR-SOU",
    name: "South Tripura",
    state: "Tripura",
    lat: 23.23,
    lng: 91.48,
    slope: 19,
    elevation: 90,
    historicalEvents: 4,
    exposedPopulation: 1240,
    roadCutIndex: 0.44,
    soilClass: "Fine loamy",
  },
  {
    id: "TR-NOR",
    name: "North Tripura",
    state: "Tripura",
    lat: 24.32,
    lng: 92.15,
    slope: 23,
    elevation: 210,
    historicalEvents: 5,
    exposedPopulation: 1080,
    roadCutIndex: 0.5,
    soilClass: "Clayey",
  },
];

export const NER_STATES: NerState[] = [
  "Arunachal Pradesh",
  "Assam",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Sikkim",
  "Tripura",
];

export const ALL_INDIAN_STATES: string[] = [
  // North Eastern Region (Priority)
  "Arunachal Pradesh",
  "Assam",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Sikkim",
  "Tripura",
  // Other Indian States
  "Andhra Pradesh",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Tamil Nadu",
  "Telangana",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  // Union Territories
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const NER_CENTER: [number, number] = [25.9, 92.9];
