/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as EmergencyResponseRouteImport } from './routes/emergency-response'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as LifelinesRouteImport } from './routes/lifelines'
import { Route as MapRouteImport } from './routes/map'
import { Route as RainfallRouteImport } from './routes/rainfall'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RiskZonesRouteImport } from './routes/risk-zones'
import { Route as RoadsRouteImport } from './routes/roads'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthorityAlertsRouteImport } from './routes/authority.alerts'
import { Route as AuthorityMfaRouteImport } from './routes/authority.mfa'
import { Route as AuthoritySecurityRouteImport } from './routes/authority.security'
import { Route as AuthorityVerifyRouteImport } from './routes/authority.verify'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenAlertsRouteImport } from './routes/citizen.alerts'
import { Route as CitizenMapRouteImport } from './routes/citizen.map'
import { Route as CitizenProfileRouteImport } from './routes/citizen.profile'
import { Route as CitizenReportRouteImport } from './routes/citizen.report'
import { Route as CitizenSafetyRouteImport } from './routes/citizen.safety'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsNewRouteImport } from './routes/reports.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyResponseRoute = EmergencyResponseRouteImport.update({
  id: '/emergency-response',
  path: '/emergency-response',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const LifelinesRoute = LifelinesRouteImport.update({
  id: '/lifelines',
  path: '/lifelines',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const RainfallRoute = RainfallRouteImport.update({
  id: '/rainfall',
  path: '/rainfall',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskZonesRoute = RiskZonesRouteImport.update({
  id: '/risk-zones',
  path: '/risk-zones',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsRoute = RoadsRouteImport.update({
  id: '/roads',
  path: '/roads',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityAlertsRoute = AuthorityAlertsRouteImport.update({
  id: '/authority/alerts',
  path: '/authority/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityMfaRoute = AuthorityMfaRouteImport.update({
  id: '/authority/mfa',
  path: '/authority/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthoritySecurityRoute = AuthoritySecurityRouteImport.update({
  id: '/authority/security',
  path: '/authority/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityVerifyRoute = AuthorityVerifyRouteImport.update({
  id: '/authority/verify',
  path: '/authority/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/citizen/',
  path: '/citizen/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenAlertsRoute = CitizenAlertsRouteImport.update({
  id: '/citizen/alerts',
  path: '/citizen/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenMapRoute = CitizenMapRouteImport.update({
  id: '/citizen/map',
  path: '/citizen/map',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenProfileRoute = CitizenProfileRouteImport.update({
  id: '/citizen/profile',
  path: '/citizen/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenReportRoute = CitizenReportRouteImport.update({
  id: '/citizen/report',
  path: '/citizen/report',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenSafetyRoute = CitizenSafetyRouteImport.update({
  id: '/citizen/safety',
  path: '/citizen/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsNewRoute = ReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/command-center': typeof CommandCenterRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/emergency-response': typeof EmergencyResponseRoute
  '/forecast': typeof ForecastRoute
  '/lifelines': typeof LifelinesRoute
  '/map': typeof MapRoute
  '/rainfall': typeof RainfallRoute
  '/resources': typeof ResourcesRoute
  '/risk-zones': typeof RiskZonesRoute
  '/roads': typeof RoadsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/authority/alerts': typeof AuthorityAlertsRoute
  '/authority/mfa': typeof AuthorityMfaRoute
  '/authority/security': typeof AuthoritySecurityRoute
  '/authority/verify': typeof AuthorityVerifyRoute
  '/citizen/alerts': typeof CitizenAlertsRoute
  '/citizen/map': typeof CitizenMapRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/safety': typeof CitizenSafetyRoute
  '/reports/new': typeof ReportsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/command-center': typeof CommandCenterRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/emergency-response': typeof EmergencyResponseRoute
  '/forecast': typeof ForecastRoute
  '/lifelines': typeof LifelinesRoute
  '/map': typeof MapRoute
  '/rainfall': typeof RainfallRoute
  '/resources': typeof ResourcesRoute
  '/risk-zones': typeof RiskZonesRoute
  '/roads': typeof RoadsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/authority/alerts': typeof AuthorityAlertsRoute
  '/authority/mfa': typeof AuthorityMfaRoute
  '/authority/security': typeof AuthoritySecurityRoute
  '/authority/verify': typeof AuthorityVerifyRoute
  '/citizen/alerts': typeof CitizenAlertsRoute
  '/citizen/map': typeof CitizenMapRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/safety': typeof CitizenSafetyRoute
  '/reports/new': typeof ReportsNewRoute
  '/admin': typeof AdminIndexRoute
  '/citizen': typeof CitizenIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/command-center': typeof CommandCenterRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/emergency-response': typeof EmergencyResponseRoute
  '/forecast': typeof ForecastRoute
  '/lifelines': typeof LifelinesRoute
  '/map': typeof MapRoute
  '/rainfall': typeof RainfallRoute
  '/resources': typeof ResourcesRoute
  '/risk-zones': typeof RiskZonesRoute
  '/roads': typeof RoadsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/authority/alerts': typeof AuthorityAlertsRoute
  '/authority/mfa': typeof AuthorityMfaRoute
  '/authority/security': typeof AuthoritySecurityRoute
  '/authority/verify': typeof AuthorityVerifyRoute
  '/citizen/alerts': typeof CitizenAlertsRoute
  '/citizen/map': typeof CitizenMapRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/safety': typeof CitizenSafetyRoute
  '/reports/new': typeof ReportsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/auth'
    | '/command-center'
    | '/dashboard'
    | '/data-sources'
    | '/digital-twin'
    | '/emergency-response'
    | '/forecast'
    | '/lifelines'
    | '/map'
    | '/rainfall'
    | '/resources'
    | '/risk-zones'
    | '/roads'
    | '/sensors'
    | '/settings'
    | '/simulator'
    | '/sitemap.xml'
    | '/authority/alerts'
    | '/authority/mfa'
    | '/authority/security'
    | '/authority/verify'
    | '/citizen/alerts'
    | '/citizen/map'
    | '/citizen/profile'
    | '/citizen/report'
    | '/citizen/safety'
    | '/reports/new'
    | '/admin/'
    | '/citizen/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/auth'
    | '/command-center'
    | '/dashboard'
    | '/data-sources'
    | '/digital-twin'
    | '/emergency-response'
    | '/forecast'
    | '/lifelines'
    | '/map'
    | '/rainfall'
    | '/resources'
    | '/risk-zones'
    | '/roads'
    | '/sensors'
    | '/settings'
    | '/simulator'
    | '/sitemap.xml'
    | '/authority/alerts'
    | '/authority/mfa'
    | '/authority/security'
    | '/authority/verify'
    | '/citizen/alerts'
    | '/citizen/map'
    | '/citizen/profile'
    | '/citizen/report'
    | '/citizen/safety'
    | '/reports/new'
    | '/admin'
    | '/citizen'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/auth'
    | '/command-center'
    | '/dashboard'
    | '/data-sources'
    | '/digital-twin'
    | '/emergency-response'
    | '/forecast'
    | '/lifelines'
    | '/map'
    | '/rainfall'
    | '/resources'
    | '/risk-zones'
    | '/roads'
    | '/sensors'
    | '/settings'
    | '/simulator'
    | '/sitemap.xml'
    | '/authority/alerts'
    | '/authority/mfa'
    | '/authority/security'
    | '/authority/verify'
    | '/citizen/alerts'
    | '/citizen/map'
    | '/citizen/profile'
    | '/citizen/report'
    | '/citizen/safety'
    | '/reports/new'
    | '/admin/'
    | '/citizen/'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CommandCenterRoute: typeof CommandCenterRoute
  DashboardRoute: typeof DashboardRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  EmergencyResponseRoute: typeof EmergencyResponseRoute
  ForecastRoute: typeof ForecastRoute
  LifelinesRoute: typeof LifelinesRoute
  MapRoute: typeof MapRoute
  RainfallRoute: typeof RainfallRoute
  ResourcesRoute: typeof ResourcesRoute
  RiskZonesRoute: typeof RiskZonesRoute
  RoadsRoute: typeof RoadsRoute
  SensorsRoute: typeof SensorsRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthorityAlertsRoute: typeof AuthorityAlertsRoute
  AuthorityMfaRoute: typeof AuthorityMfaRoute
  AuthoritySecurityRoute: typeof AuthoritySecurityRoute
  AuthorityVerifyRoute: typeof AuthorityVerifyRoute
  CitizenAlertsRoute: typeof CitizenAlertsRoute
  CitizenMapRoute: typeof CitizenMapRoute
  CitizenProfileRoute: typeof CitizenProfileRoute
  CitizenReportRoute: typeof CitizenReportRoute
  CitizenSafetyRoute: typeof CitizenSafetyRoute
  ReportsNewRoute: typeof ReportsNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-response': {
      id: '/emergency-response'
      path: '/emergency-response'
      fullPath: '/emergency-response'
      preLoaderRoute: typeof EmergencyResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifelines': {
      id: '/lifelines'
      path: '/lifelines'
      fullPath: '/lifelines'
      preLoaderRoute: typeof LifelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rainfall': {
      id: '/rainfall'
      path: '/rainfall'
      fullPath: '/rainfall'
      preLoaderRoute: typeof RainfallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-zones': {
      id: '/risk-zones'
      path: '/risk-zones'
      fullPath: '/risk-zones'
      preLoaderRoute: typeof RiskZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roads': {
      id: '/roads'
      path: '/roads'
      fullPath: '/roads'
      preLoaderRoute: typeof RoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/alerts': {
      id: '/authority/alerts'
      path: '/authority/alerts'
      fullPath: '/authority/alerts'
      preLoaderRoute: typeof AuthorityAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/mfa': {
      id: '/authority/mfa'
      path: '/authority/mfa'
      fullPath: '/authority/mfa'
      preLoaderRoute: typeof AuthorityMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/security': {
      id: '/authority/security'
      path: '/authority/security'
      fullPath: '/authority/security'
      preLoaderRoute: typeof AuthoritySecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/verify': {
      id: '/authority/verify'
      path: '/authority/verify'
      fullPath: '/authority/verify'
      preLoaderRoute: typeof AuthorityVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/citizen'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/alerts': {
      id: '/citizen/alerts'
      path: '/citizen/alerts'
      fullPath: '/citizen/alerts'
      preLoaderRoute: typeof CitizenAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/map': {
      id: '/citizen/map'
      path: '/citizen/map'
      fullPath: '/citizen/map'
      preLoaderRoute: typeof CitizenMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/profile': {
      id: '/citizen/profile'
      path: '/citizen/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof CitizenProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/report': {
      id: '/citizen/report'
      path: '/citizen/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/safety': {
      id: '/citizen/safety'
      path: '/citizen/safety'
      fullPath: '/citizen/safety'
      preLoaderRoute: typeof CitizenSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/new': {
      id: '/reports/new'
      path: '/reports/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof ReportsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CommandCenterRoute: CommandCenterRoute,
  DashboardRoute: DashboardRoute,
  DataSourcesRoute: DataSourcesRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  EmergencyResponseRoute: EmergencyResponseRoute,
  ForecastRoute: ForecastRoute,
  LifelinesRoute: LifelinesRoute,
  MapRoute: MapRoute,
  RainfallRoute: RainfallRoute,
  ResourcesRoute: ResourcesRoute,
  RiskZonesRoute: RiskZonesRoute,
  RoadsRoute: RoadsRoute,
  SensorsRoute: SensorsRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthorityAlertsRoute: AuthorityAlertsRoute,
  AuthorityMfaRoute: AuthorityMfaRoute,
  AuthoritySecurityRoute: AuthoritySecurityRoute,
  AuthorityVerifyRoute: AuthorityVerifyRoute,
  CitizenAlertsRoute: CitizenAlertsRoute,
  CitizenMapRoute: CitizenMapRoute,
  CitizenProfileRoute: CitizenProfileRoute,
  CitizenReportRoute: CitizenReportRoute,
  CitizenSafetyRoute: CitizenSafetyRoute,
  ReportsNewRoute: ReportsNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  CitizenIndexRoute: CitizenIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
